# mkdir /mnt/sdb/svn/config/svn_TDD16
# chown 1000:1000 /mnt/sdb/svn/config

version: "3.3"
services:
 svn_TDD16:
   container_name: svn_TDD16
   restart: always
   image: sdorra/scm-manager:1.60
   volumes:
     - /mnt/sdb/svn/config/svn_TDD16:/var/lib/scm
     - $PWD/server-config-TDD16.xml:/opt/scm-server/conf/server-config.xml:z
     - $PWD/logs/TDD16:/var/lib/scm/logs:z 
   environment:
     - TZ=Asia/Taipei
   ports:
     - "8180:8080"
#   network_mode: "host"
 svn_TDD52:
   container_name: svn_TDD52
   restart: always
   image: sdorra/scm-manager:1.60
   volumes:
     - /mnt/sdb/svn/config/svn_TDD52:/var/lib/scm
     - $PWD/server-config-TDD52.xml:/opt/scm-server/conf/server-config.xml:z
     - $PWD/logs/TDD52:/var/lib/scm/logs:z
   environment:
     - TZ=Asia/Taipei
   ports:
     - "8181:8080"
